# Generated by Django 4.1.1 on 2022-12-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixas',
            name='name',
        ),
        migrations.AddField(
            model_name='caixas',
            name='option',
            field=models.CharField(choices=[('frios', 'frios'), ('presente', 'presente'), ('entrega', 'entrega')], default='presente', max_length=24),
        ),
    ]
